name: CI

on: push

jobs:
  build_and_check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3.0.11
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build and test
        uses: eskatos/gradle-command-action@v2
        with:
          arguments: build
