name: CI

on: push

jobs:
  build_and_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
